name: Generate Tokens

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.13.0'

      - name: Run generate tokens
        run: dart tool/generate_tokens.dart

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: update generated tokens" || echo "No changes to commit"
          git push https://USERNAME:${{ secrets.PAT_TOKEN }}@github.com/dharmahermanda-001/mds-token.git main
