name: Generate Tokens

on:
  push:
    paths:
      - "tokens/tokens.json"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0" # sesuaikan versi Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Tokens
        run: dart tool/generate_tokens.dart

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lib/generated/
          git commit -m "chore: update generated tokens"
          git push
        continue-on-error: true
