name: Generate Tokens and Bump Version

on:
  push:
    paths:
      - "tokens/tokens.json"
  workflow_dispatch:

jobs:
  generate_and_bump:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Generate tokens
      - name: Generate Tokens
        run: dart tool/generate_tokens.dart

      # 5. Commit generated files
      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/fmi_core/lib/design_tokens/mds_tokens.dart
          git commit -m "chore: update generated tokens" || echo "No token changes"

      # 6. Bump version in pubspec.yaml
      - name: Bump version
        run: |
          FILE="packages/fmi_core/pubspec.yaml"
          VERSION=$(grep '^version:' $FILE | awk '{print $2}')
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"
          echo "Bumping version: $VERSION → $NEW_VERSION"
          sed -i "s/^version: .*/version: $NEW_VERSION/" $FILE
          git add $FILE
          git commit -m "chore(fmi_core): bump version to $NEW_VERSION" || echo "No version change"

      # 7. Push back to repo
      - name: Push changes
        env:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/dharmahermanda-001/mds-token.git HEAD:main
