name: Generate Tokens and Auto Bump

on:
  push:
    paths:
      - "tokens/tokens.json"
      - "packages/fmi_core/**"
  workflow_dispatch:

jobs:
  generate_and_bump:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }} # pakai PAT supaya bisa push balik

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Generate tokens
      - name: Generate Tokens
        run: dart tool/generate_tokens.dart

      # 5. Bump pubspec.yaml version
      - name: Read and bump version
        id: bump
        run: |
          FILE="packages/fmi_core/pubspec.yaml"
          old_version=$(grep '^version:' $FILE | awk '{print $2}')
          new_version=$(echo $old_version | awk -F. -v OFS=. '{$NF++;print}')
          echo "Old version: $old_version"
          echo "New version: $new_version"
          sed -i "s/^version: .*/version: $new_version/" $FILE
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      # 6. Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/fmi_core/pubspec.yaml
          git add packages/fmi_core/lib/design_tokens/mds_tokens.dart
          git commit -m "chore(fmi_core): bump version to ${{ steps.bump.outputs.new_version }} [skip ci]" || echo "No changes"

      # 7. Push back to repo
      - name: Push changes
        env:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/dharmahermanda-001/mds-token.git HEAD:main

      # 8. Create tag for version
      - name: Create and push tag
        if: ${{ steps.bump.outputs.new_version != '' }}
        env:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          TAG="fmi_core-v${{ steps.bump.outputs.new_version }}"
          git tag $TAG
          git push https://x-access-token:${GH_PAT}@github.com/dharmahermanda-001/mds-token.git $TAG
