name: Generate Tokens

on:
  push:
    paths:
      - "tokens/tokens.json"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Tokens
        run: dart tool/generate_tokens.dart
      
      - name: Override remote with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/dharmahermanda-001/mds-token.git
        
      - name: Commit generated files
        run: |
          git config user.name "dharma hermanda"
          git config user.email "dharma_hermanda@kamoro.com"
          git add lib/generated/
          git commit -m "chore: update generated tokens" || echo "No changes to commit"
          git push origin HEAD:main
